name = "Piekarnia Modpack"
author = "Jakub"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6936cf73529367731e59cd49b0a4c35f1d62be8d87e0e9016db2524c08cd0029"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
