name = "Piekarnia Modpack"
author = "Jakub"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95285b97f26b9ff131a99c458a51a20a910cd6b98a7010326f882d9f30ffa9af"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
