name = "Piekarnia Modpack"
author = "Jakub"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ac69d3d7b0380a9354820f53e7001e7ca7a9cd13e796bcc0e96626c816d8069"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
